 export const data = [
   {
    id: '1',
    name: ' Sardorbek Mukhtorov',
    age: '26',
    address: 'Namangan',
    status: 'Student',
    nickname: 'Ali',
    univ: 'sejong',
    job: 'developer',
   },
   {
    id: '2',
    name: ' Sardorbek Mukhtorov',
    age: '18',
    address: 'gwanjinggu',
    status: 'Student',
    nickname: 'Ali',
    univ: 'sejong',
    job: 'developer',
   },
   {
    id: '3',
    name: ' Sardorbek Mukhtorov',
    age: '27',
    address: 'Namangan',
    status: 'Student',
    nickname: 'Ali',
    univ: 'sejong',
    job: 'developer',
   },
   {
    id: '4',
    name: ' Sardorbek Mukhtorov',
    age: '27',
    address: 'gunjadong',
    status: 'Student',
    nickname: 'Ali',
    univ: 'sejong',
    job: 'developer',
   },
   {
    id: '5',
    name: ' Sardorbek adamson',
    age: '27',
    address: 'seoul',
    status: 'Student',
    nickname: 'Ali',
    univ: 'sejong',
    job: 'developer',
   },
   {
    id: '6',
    name: ' john Mukhtorov',
    age: '72',
    address: 'boston',
    status: 'Student',
    nickname: 'Ali',
    univ: 'sejong',
    job: 'developer',
   },
   {
    id: '7',
    name: ' dev Mukhtorov',
    age: '27',
    address: 'Namangan',
    status: 'Student',
    nickname: 'Ali',
    univ: 'sejong',
    job: 'developer',
   },
   {
    id: '8',
    name: ' Sardorbek Mukhtorov',
    age: '64',
    address: 'Namangan',
    status: 'Student',
    nickname: 'Ali',
    univ: 'sejong',
    job: 'developer',
   },
   {
    id: '9',
    name: ' Sardorbek Mukhtorov',
    age: '27',
    address: 'Namangan',
    status: 'Student',
    nickname: 'Ali',
    univ: 'sejong',
    job: 'developer',
   },
   {
    id: '10',
    name: ' Sardorbek Mukhtorov',
    age: '27',
    address: 'Namangan',
    status: 'Student',
    nickname: 'Ali',
    univ: 'sejong',
    job: 'developer',
   },
  ]